# Introduction to Deep Learning with PyTorch

https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/introduction-to-pytorch?ex=1#_=_
    
    
#### 01 Introduction to PyTorch

In this first chapter, we introduce basic concepts of neural networks and deep learning using PyTorch library.

introduction to PyTorch, creating tensors in PyTorch, Matrix multiplication, forward propagation, forward pass, backpropagation by hand, backpropagation using PyTorch, Calculating gradiens in Pytorch, introduction to neural networks, your first neural network, your first PyTorch neural network.



#### 02 Artificial Neural Networks

In this second chapter, we delve deeper into Artificial Neural Networks, learning how to train them with real datasets.

Activation functions, Neural networks, ReLU activation, Loss functions, Calculation Loss function by hand, calculating loss function in PyTorch, Loss function of random scores, Preparing a dataset in PyTorch, Preparing MNist DATASET, inspecting the dataloaders, training neural networks, building a neural network, training a neural network, using the network to make predictions

#### 03 Convolutional Neural Networks (CNNs)

In this third chapter, we introduce convolutional neural networks, learning how to train them and how to use them to make predictions

Convolution operators, convolution operator - OOP way, convolution operator - functional way, pooling operators, max-pooling operator, convolutional neural networks, your first CNN - __init__ method, your first CNN - forward() method
Training Convolutional Neural Networks, Training CNNs, Using CNNs to make predictions

#### 04 Using Convolutional Neural Networks

In this last chapter, we learn how to make neural networks work well in practice, using concepts like regularization, batch-normalization and transfer learning.

The sequential module, sequential module  - init method, sequential module -forward() method, the problem of overfitting, validation set, detecting overfitting, regulatization techniques, L2 - regulatization, dropout, batch-normalization, transfer learning, Finetunning a CNN, torchvision module


https://towardsdatascience.com/what-is-pytorch-a84e4559f0e3


#### Introduction to PyTorch

###### Creating tensors in PyTorch
Random tensors are very important in neural networks. Parameters of the neural networks typically are initialized with random weights (random tensors).

Let us start practicing building tensors in PyTorch library. As you know, tensors are arrays with an arbitrary number of dimensions, corresponding to NumPy's ndarrays. You are going to create a random tensor of sizes 3 by 3 and set it to variable your_first_tensor. Then, you will need to print it. Finally, calculate its size in variable tensor_size and print its value.

Import PyTorch main library.
Create the variable your_first_tensor and set it to a random torch tensor of size 3 by 3.
Calculate its shape (dimension sizes) and set it to variable tensor_size.
Print the values of your_first_tensor and tensor_size


In [1]:
import torch

In [2]:
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

build first PyTorch tensor

In [3]:
# Import torch
import torch

# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.1530, 0.3138, 0.8175],
        [0.7288, 0.7483, 0.7158],
        [0.8853, 0.1551, 0.4494]])
torch.Size([3, 3])


##### Matrix multiplication
There are many important types of matrices which have their uses in neural networks. Some important matrices are matrices of ones (where each entry is set to 1) and the identity matrix (where the diagonal is set to 1 while all other values are 0). The identity matrix is very important in linear algebra: any matrix multiplied with identity matrix is simply the original matrix.

Let us experiment with these two types of matrices. You are going to build a matrix of ones with shape 3 by 3 called tensor_of_ones and an identity matrix of the same shape, called identity_tensor. We are going to see what happens when we multiply these two matrices, and what happens if we do an element-wise multiplication of them.

Create a matrix of ones with shape 3 by 3, and put it on variable tensor_of_ones.
Create an identity matrix with shape 3 by 3, and put it on variable identity_tensor.
Do a matrix multiplication of tensor_of_ones with identity_tensor and print its value.
Do an element-wise multiplication of tensor_of_ones with identity_tensor and print its value.


In [4]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
# identity matrix is where the diagonal is set to 1 while all other values are 0
# The identity matrix is very important in linear algebra: any matrix multiplied
# with identity matrix is simply the original matrix.
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones * identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


matrices_multiplied is same as tensor_of_ones (because identity matrix is the neutral element in matrix multiplication, the product of any matrix multiplied with it gives the original matrix), while element_multiplication is same as identity_tensor.

#### Forward propagation
https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/introduction-to-pytorch?ex=4



In [1]:
import torch
a = torch.Tensor([2])
b = torch.Tensor([-4])
c = torch.Tensor([-2])
d = torch.Tensor([2])

e= a + b
f= c * d

g= e *f
print(e,f,g)

tensor([-2.]) tensor([-4.]) tensor([8.])


#### Forward pass
Let's have something resembling more a neural network. The computational graph has been given below. You are going to initialize 3 large random tensors, and then do the operations as given in the computational graph. The final operation is the mean of the tensor, given by torch.mean(your_tensor).

Initialize random tensors x, y and z, each having shape (1000, 1000).
Multiply x with y, putting the result in tensor q.
Do an elementwise multiplication of tensor z with tensor q, putting the results in f

In [2]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x,y)
# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(125.2134)


You just built a nice computational graph containing 5'000'001 values. In the next lesson, you are going to compute the gradients of this graph.

### Backpropagation
https://classroom.udacity.com/courses/ud188/lessons/b4ca7aaa-b346-43b1-ae7d-20d27b2eab65/concepts/4cc13714-37d7-4705-a714-314ede5290b5
Now, we're ready to get our hands into training a neural network. For this, we'll use the method known as backpropagation. In a nutshell, backpropagation will consist of:

Doing a feedforward operation.
Comparing the output of the model with the desired output.
Calculating the error.
Running the feedforward operation backwards (backpropagation) to spread the error to each of the weights.
Use this to update the weights, and get a better model.
Continue this until we have a model that is good.
Sounds more complicated than what it actually is. Let's take a look in the next few videos. The first video will show us a conceptual interpretation of what backpropagation is.

#### Backpropagation  by auto-differentiation
main algorithm in neural networks,
Derivatives - represent a rate of change in a function
can be described as steepnees of the function

Derivatives rules
(f+g)' = f' + g'
(f*g)'= f*dg + g*df
(x^n)' = d/dx  x^n = nx^(n-1)
(1/x)' = - 1/x^2
(f/g)' = (df * 1/g) + (-1/g^2  dg *f)


chain rule

d/dx [(f(x))^n] = n(f(x))^n-1 * f'(x)

d/dx [f(g(x))] = f'(g(x))g'(x)

gradient is multivariable generalization of the derivative

#### backpropagation in Python

In [ ]:
import torch
x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(-2., requires_grad=True)
q = x + y 
f = q * z
f.backward()

print('Gradient of z is:' +str(z.grad))
print('Gradient of y is:' +str(y.grad))
print('Gradient of x is:' +str(x.grad))

Congratulations, you know how to compute derivatives! While PyTorch computes derivatives for you, mastering them will make you a much better deep learning practitioner and that knowledge will guide you in training neural networks better.

##### Backpropagation using PyTorch
Here, you are going to use automatic differentiation of PyTorch in order to compute the derivatives of x, y and z from the previous exercise.

Initialize tensors x, y and z to values 4, -3 and 5.
Put the sum of tensors x and y in q, put the product of q and z in f.
Calculate the derivatives of the computational graph.
Print the gradients of the x, y and z tensors.

Initialize tensors x, y and z to values 4, -3 and 5.
Put the sum of tensors x and y in q, put the product of q and z in f.
Calculate the derivatives of the computational graph.
Print the gradients of the x, y and z tensors.

In [3]:
import torch
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)
q = x + y 
f = q * z

#calculate derivative
f.backward()

print('Gradient of z is:' +str(z.grad))
print('Gradient of y is:' +str(y.grad))
print('Gradient of x is:' +str(x.grad))

Gradient of z is:tensor(1.)
Gradient of y is:tensor(5.)
Gradient of x is:tensor(5.)


###### Calculating gradients in PyTorch
Remember the exercise in forward pass? Now that you know how to calculate derivatives, let's make a step forward and start calculating the gradients (derivatives of tensors) of the computational graph you built back then. We have already initialized for you three random tensors of shape (1000, 1000) called x, y and z. First, we multiply tensors x and y, then we do an elementwise multiplication of their product with tensor z, and then we compute its mean. In the end, we compute the derivatives.

The main difference from the previous exercise is the scale of the tensors. While before, tensors x, y and z had just 1 number, now they each have 1 million numbers.

Multiply tensors x and y, put the product in tensor q.
Do an elementwise multiplication of tensors z with q.
Calculate the gradients.



In [7]:
x = torch.rand(1000, 1000, requires_grad=True)
y = torch.rand(1000, 1000, requires_grad=True)
z = torch.rand(1000, 1000, requires_grad=True)
# Multiply tensors x and y
q = torch.matmul(x,y)


# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward()

In general, calculating gradients is as easy as calculating derivatives in PyTorch. Obviously, if the tensors are very large (billions of values) then the calculation might take some time.

#### Introduction to Neural Networks



Your first neural network
You are going to build a neural network in PyTorch, using the hard way. Your input will be images of size (28, 28), so images containing 784 pixels. Your network will contain an input_layer, a hidden layer with 200 units, and an output layer with 10 classes. The input layer has already been created for you. You are going to create the weights, and then do matrix multiplications, getting the results from the network.

Initialize with random numbers two matrices of weights, called weight_1 and weight_2.
Set the result of input_layer times weight_1 to hidden_1. Set the result of hidden_1 times weight_2 to output_layer.

https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/introduction-to-pytorch?ex=11

In [2]:
import torch

# Your input will be images of size (28, 28), so images containing 784 pixels
input_layer = torch.rand(784)

# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([20813.0352, 20862.6406, 19335.0664, 18141.1523, 19175.9766, 18487.1172,
        19634.6035, 19910.5176, 19620.8281, 19092.0410])


For the most part, neural networks are just matrix (tensor) multiplication. This is the reason why we have put so much emphasis on matrices and tensors!

Your first PyTorch neural network
You are going to build the same neural network you built in the previous exercise, but now using the PyTorch way. As a reminder, you have 784 units in the input layer, 200 hidden units and 10 units for the output layer.

Instantiate two linear layers calling them self.fc1 and self.fc2. Determine their correct dimensions.
Implement the .forward() method, using the two layers you defined and returning x.


In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784,200)
        self.fc2 = nn.Linear(200,10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

Cool! You just built your first PyTorch artificial neural network. You are going to build many more during this course.

#### 02 Artificial Neural Networks

##### Activation functions


###### simple neural network

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

input_layer = torch.tensor([2.,1.])
weight_1= torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
hidden_layer = torch.matmul(input_layer, weight_1)

weight_2= torch.tensor([[0.48, 0.12], [0.64, 0.91]])
output_layer = torch.matmul(hidden_layer, weight_2)
print(output_layer)


tensor([0.9696, 0.9399])


In [2]:
#matrix multiplication is a linear transformation

weight_1= torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
weight_2= torch.tensor([[0.48, 0.12], [0.64, 0.91]])

weight = torch.matmul(weight_1, weight_2)


output_layer = torch.matmul(input_layer, weight)
print(output_layer)
print(weight)


tensor([0.9696, 0.9399])
tensor([[0.4208, 0.3452],
        [0.1280, 0.2495]])


##### Non linear split of data
We use activatin fuctions to split non-linear data 
Examples of activation functions: Sigmoid, tanh, ReLU, Leaky ReLU, Maxout, ELU

The most used is ReLU (rectified linear unit), even for most complex imaging problems
ReLU(x) = max(0,x)

In [3]:
import torch.nn as nn
relu = nn.ReLU()
tensor_1 = torch.tensor([2., -4.])
print(relu(tensor_1))

tensor_2 = torch.tensor([[2.,-4.],
                        [1.2, 0.]])
print(relu(tensor_2))

tensor([2., 0.])
tensor([[2.0000, 0.0000],
        [1.2000, 0.0000]])


In ReLU positive inputs conserved, negative zeroed
Lets use other activation functions


Neural networks
Let us see the differences between neural networks which apply ReLU and those which do not apply ReLU. We have already initialized the input called input_layer, and three sets of weights, called weight_1, weight_2 and weight_3.

We are going to convince ourselves that networks with multiple layers which do not contain non-linearity can be expressed as neural networks with one layer.

The network and the shape of layers and weights is shown below.


Calculate the first and second hidden layer by multiplying the appropriate inputs with the corresponding weights.
Calculate and print the results of the output.
Set weight_composed_1 to the product of weight_1 with weight_2, then set weight to the product of weight_composed_1 with weight_3.
Calculate and print the output.




In [4]:
input_layer = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

weight_1 = torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
                        [ 0.3327, -0.0461,  1.4473, -0.8070],
                        [ 0.0681, -0.7058, -1.8017,  0.5857],
                        [ 0.8764,  0.9618, -0.4505,  0.2888]])

weight_2 = torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
                        [-0.1092, -0.1620,  0.1951, -0.1169],
                        [-0.5120,  1.1997,  0.8483, -0.2476],
                        [-0.3369,  0.5617, -0.6658,  0.2221]])

weight_3 = torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
                        [-0.8753, -0.3277, -0.1454, -0.0167],
                        [ 0.3582,  0.3254, -1.8509, -1.4205],
                        [ 0.3786,  0.5999, -0.5665, -0.3975]])


In [5]:
# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


Results are identical!

ReLU activation
In this exercise, we have the same settings as the previous exercise. In addition, we have instantiated the ReLU activation function called relu().

Now we are going to build a neural network which has non-linearity and by doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.

Apply non-linearity on hidden_1 and hidden_2.
Apply non-linearity in the product of first two weight.
Multiply the result of the previous step with weight_3.
Multiply input_layer with weight and print the results.


In [6]:
#activation function relu
relu = nn.ReLU()
# Apply non-linearity on hidden_1 and hidden_2
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])


Awesome! As expected the results are different from the previous exercise.


ReLU activation again
Neural networks don't need to have the same number of units in each layer. Here, you are going to experiment with the ReLU activation function again, but this time we are going to have a different number of units in the layers of the neural network. The input layer will still have 4 features, but then the first hidden layer will have 6 units and the output layer will have 2 units.


Instantiate the ReLU() activation function as relu (the function is part of nn module).
Initialize weight_1 and weight_2 with random numbers.
Multiply the input_layer with weight_1, storing results in hidden_1.
Apply the relu activation function over hidden_1, and then multiply the output of it with weight_2.

In [8]:
# Instantiate ReLU activation function as relu
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers

#If the input layer has 4 units, and the hidden layer has 6 units, then 
#the weight_1 should have shape (4, 6).
weight_1 = torch.rand(4, 6)
#hidden layer 6 units, output layer 2 units
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

tensor([[0., 0.]])


Great! You can now build neural networks with different number of neurons on each layer.
#####  LOSS Functions

How to train a neural network:
Process:

Initialize neural networks with random weights
Do a forward pass
Calculate loss function (1 number)
Calcualte the gradients
Change the weights based on gradients

LOSS Functions:
For regression (least squared loss)
For classification: softmax cross-entropy loss
For more complicated problems (like obbject detection), more complicated losses

###### softmax cross-entropy loss
Loss functions must be differentiatable, otherwise we cant compute gradients

softmax is a function that transforms numbers into probabilities
First count softmax function as a probability
Than cross entropy loss which is L = -ln(probability)
If a probability is close to 1, loss is close to 0
if probability is small loss is close to infinity

##### CE loss in PyTorch

In [9]:
logits = torch.tensor([[3.2, 5.1, -1.7]])
#first class
ground_truth = torch.tensor([0])
#loss function combines softmax with cross entropy
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)
print(loss)

tensor(2.0404)


In [10]:
logits = torch.tensor([[10.2, 5.1, -1.7]])
#first class
ground_truth = torch.tensor([0])
#loss function combines softmax with cross entropy
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)
print(loss)

tensor(0.0061)


LOSS is very small in last example

In [11]:
# if -10
logits = torch.tensor([[-10, 5.1, -1.7]])
#first class
ground_truth = torch.tensor([0])
#loss function combines softmax with cross entropy
criterion = nn.CrossEntropyLoss()

loss = criterion(logits, ground_truth)
print(loss)

tensor(15.1011)


##### Calculating LOSS by hand

Let's start the exercises by calculating the loss function by hand. Don't do this exercise in PyTorch, it is important to first do it using only pen and paper (and a calculator).

We have the same example as before but now our object is actually a frog, and the predicted scores are -1.2 for class 0 (cat), 0.12 for class 1 (car) and 4.8 for class 2 (frog).

What is the result of the softmax cross-entropy loss function?

Class	Predicted Score
Cat	-1.2
Car	0.12
Frog	4.8


First exponentiate each term, then normalize the probabilities by dividing with sum, and then do -ln(probability_frog).
The base of logarithm should be e (e is approximately 2.7182818).

Calculating loss function in PyTorch
You are going to code the previous exercise, and make sure that we computed the loss correctly. Predicted scores are -1.2 for class 0 (cat), 0.12 for class 1 (car) and 4.8 for class 2 (frog). The ground truth is class 2 (frog). Compute the loss function in PyTorch.

Initialize the tensor of scores with numbers [[-1.2, 0.12, 4.8]], and the tensor of ground truth [2].
Instantiate the cross-entropy loss and call it criterion.
Compute and print the loss.

In [12]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(0.0117)


As you can see, the loss function PyTorch calculated gives the same number as the loss function you calculated. Being proficient in understanding and calculating loss functions is a very important skill in deep learning.

Loss function of random scores
If the neural network predicts random scores, what would be its loss function? Let's find it out in PyTorch. The neural network is going to have 1000 classes, each having a random score. For ground truth, it will have class 111. Calculate the loss function.

Instructions
100 XP
Import torch and torch.nn as nn
Initialize logits with a random tensor of shape (1, 1000) and ground_truth with a tensor containing the number 111.
Instantiate the cross-entropy loss in a variable called criterion.
Calculate and print the loss function.

In [13]:
# Import torch and torch.nn
import torch
import torch.nn as nn
# Initialize logits and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])


# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(7.0683)


The score is close to -ln(1/1000) = 6.9. This is not surprising, considering that scores were random and close to each other, so the probability for each class was approximately the same (1/1000) = 0.001.


#### Preparting a dataset in PyTorch

https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/artificial-neural-networks?ex=9

we will use MNIST (70 thousand hand written digits, shaped 28X28, back and white, 1 channel)
CIFAR-10( dataset with natural colored images, 32X32, RGB format 3 channels red green and blue)


In addition to torch we import torchvision
dasets needs to be in pytorch friendly format
see how we can achive this

In [ ]:
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transforms = transforms.Compose(
[transforms.ToTensor(),
transforms.Normalize((0.4914, 0.48216, 0.44653),
                    (0.24703, 0.24349, 0.26159))])


#next is to get a dataset
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, 
                                        download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, 
                                        download=True, transform=transform)

# build trainloader and testloader to make data ready for pytorch

#use only 32 randomly sampled images, dataset is too big
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                         shuffle=True, num_workers=4)
testloader = torch.utils.data.DataLoader(testset, batch_size=32,
                                         shuffle=False, num_workers=4)

#how to inspect dataset
print(testloader.dataset.test_data.shape, trainloader.dataset.train_data.shape)

#similarly we can look at batch size
print(testloader.batch_size)

# will be good to look at a type of random sampler
print(trainloader.sampler)

###### Preparing MNIST dataset
You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).

####### Instructions
100 XP
Transform the data to torch tensors and normalize it, mean is 0.1307 while std is 0.3081.
Prepare the trainset and the testset.
Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time.


In [2]:
import torch
import torch.utils.data
import torchvision
import torchvision.transforms as transforms

# Transform the data to torch tensors and normalize it
# mean is 0.1307 while std is 0.3081.
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307), (0.3081))
])

# Preparing training set and test set
trainset = torchvision.datasets.MNIST('mnist', train=True, download=True,
                                      transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, download=True,
                                     transform=transform)

# Prepare training loader and test loader
train_loader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                           shuffle=True, num_workers=0)
test_loader = torch.utils.data.DataLoader(testset, batch_size=32, 
                                          shuffle=False, num_workers=0)

Nice! Now you know how to prepare datasets in PyTorch. You are very close to reaching the grand goal, training neural networks!

Inspecting the dataloaders
Now you are going to explore a bit the dataloaders you created in the previous exercise. In particular, you will compute the shape of the dataset in addition to the minibatch size.

Instructions
100 XP
Compute the shapes of the trainset and testset.
Print the computed values.
Compute the size of the minibatch for both trainset and testset.
Print the minibatch size.



In [3]:
# Compute the shape of the training set and test set
trainset_shape = train_loader.dataset.data.shape
testset_shape = test_loader.dataset.data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and test set
trainset_batchsize = train_loader.batch_size
testset_batchsize = test_loader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


After you have armed yourself with the knowledge of building and exploring dataloaders, it is time to start training neural networks!

##### Training neural networks

Prepare data loaders
Build a neural network

loop over:
1. do a forward pass
2. calculate loss function
3. calculate gradients
4. change the weights based on gradients

Iterate over this 4 steps many times

Gradient descent - a steepness of a function
find a local minima of a function, all algorithm is based on minimizing loss of a function





In [ ]:
######  PREPARE DATASET ##################
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transforms = transforms.Compose(
[transforms.ToTensor(),
transforms.Normalize((0.4914, 0.48216, 0.44653),
                    (0.24703, 0.24349, 0.26159))])


#next is to get a dataset
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, 
                                        download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, 
                                        download=True, transform=transform)


###### prepare a class for neural network #################
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1=nn.Linear(32*32*3, 500)
        self.fc2=nn.Linear(500,10)
    
    def forward(self, x):
        x=F.relu(self.fc1(x))
        return self.fc2(x)
    
#start the training
net=Net()
#cross entropy
criterion = nn.CrossEntropyLoss()
#optimizer Adam, works well, version of gradient descent
optimizer = optim.Adam(net.parameters(), lr=3e-4)

for epoch in range(10):  #loop over the dataset multiple times
    for i, data in enumerate(trainloader, 0):
        #get the inputs
        inputs, labels = data
        inputs = inputs.view(1, 32*32*3)
        
        #zero the parameter gradients
        optimizer.zero_grad()
        
        #forward and backward + optimize
        #forward to output
        outputs = net(inputs)
        # compute loss function
        loss=criterion(outputs, labels)
        # gradients using loss.divert
        loss.backward()
        # change weights
        optimizer.step()
        
# using the trained net to get predictions
correct, total = 0,0
predictions = []
#set a model in evaluation mode
net.eval()

for i, data in enumerate(testloader, 0):
    inputs, labels.view(-1, 32*32*3)
    outputs = net(inputs)
    -, predicted = torch.max(outputs.data, 1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('the testing set accuracy of \
      the network is : %d %%' % (100 * correct / total))

Building a neural network - again
You haven't created a neural network since the end of the first chapter, so this is a good time to build one (practice makes perfect). Build a class for a neural network which will be used to train on the MNIST dataset. The dataset contains images of shape (28, 28, 1), so you should deduct the size of the input layer. For hidden layer use 200 units, while for output layer use 10 units (1 for each class). For activation function, use relu in a functional way (nn.Functional is already imported as F).

For context, the same net will be trained and used to make predictions in the next two exercises.

Instructions
100 XP
Define the class called Net which inherits from nn.Module.
In the __init__() method, define the parameters for the two fully connected layers.
In the .forward() method, do the forward step.

In [4]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Define the class Net
class Net(nn.Module):
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        #The dataset contains images of shape (28, 28, 1), so you
        #should deduct the size of the input layer. For hidden layer
        #use 200 units
        self.fc1 = nn.Linear(28 * 28 * 1, 200)
        
        # while for output layer use 10 units (1 for each class). 
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):   
    	# Do the forward pass
        #for activation function, use relu in a functional way
        #(nn.Functional
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

Training a neural network
Given the fully connected neural network (called model) which you built in the previous exercise and a train loader called train_loader containing the MNIST dataset (which we created for you), you're to train the net in order to predict the classes of digits. You will use the Adam optimizer to optimize the network, and considering that this is a classification problem you are going to use cross entropy as loss function.

Instructions
100 XP
Instantiate the Adam optimizer with learning rate 3e-4 and instantiate Cross-Entropy as loss function.
Complete a forward pass on the neural network using the input data.
Using backpropagation, compute the gradients of the weights, and then change the weights using the Adam optimizer.


In [5]:
import torch.optim as optim


# Instantiate the Adam optimizer and Cross-Entropy loss function
model = Net()   
#initiate Adam optimizer
#learning rate 3e-4
optimizer = optim.Adam(model.parameters(), lr=3e-4)
#instantiate cross-entropy as loss function
criterion = nn.CrossEntropyLoss()
  
for batch_idx, data_target in enumerate(train_loader):
    data = data_target[0]
    target = data_target[1]
    
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass on the neural network
    #using the input data
    output = model(data)

    # Compute the loss, gradients and change the weights
   # Using backpropagation, compute the gradients of the #weights, and then change the weights using the Adam #optimizer.
    loss = criterion(output,target )
    loss.backward()
    optimizer.step()

Using the network to make predictions
Now that you have trained the network, use it to make predictions for the data in the testing set. The network is called model (same as in the previous exercise), and the loader is called test_loader. We have already initialized variables total and correct to 0.

Instructions
100 XP
Set the network in testing (eval) mode.
Put each image into a vector using inputs.view(-1, number_of_features) where the number of features should be deducted by multiplying spatial dimensions (shape) of the image.
Do the forward pass and put the predictions in output variable.

In [7]:
correct, total = 0, 0

# Set the model in eval mode
model.eval()


for i, data in enumerate(test_loader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    # where the number of features should be deducted by #multiplying spatial dimensions (shape) of the image
    inputs = inputs.view(-1, 28 * 28)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    _, outputs = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

The testing set accuracy of the network is: 94 %


Congratulations, you are able to use neural networks to make predictions. NB: The accuracy of the net is too low compared to what we can do with neural networks. We used only a subpart of the dataset in order for the training to happen fast. You can achieve a much higher accuracy by using the entire dataset, and by using a larger neural network.

## Convolutional Neural Networks (CNNs)


#### Convolutional operator
Fully connected neural networks come with a few problems:
do you need to consider all the relations between the features?
fully connected neural networks are big and so very computationally inefficient
they have so many parameters and so overfit

2 Main ideas mitigating these problems
Units are connected with only a few units from the previos layer
Units share weights

CNNs solves this problem

Idea of convolution is simple: 
convolve an image with a filter (weights of network)
Convolving = dot product between image and filter

After that we get an activation map (also feature map)
(size of filter must be smaller that size of the image)

Convolutional layer contains multiple activation maps

If we want the size of activation map to match the size of an image we can do padding, adding zeroes at the edge of the image

There are 2 ways of using CNN's  in PyTorch
OOP-based (torch.nn) and Functional (torch.nn.functional)

##### OOP-based (torch.nn)
in_channels (int) Number of channels in input
out_channels (int) number of channels produced by the convolution
kernel_size (int or tuple) size of convolving kernel

stride (int or tuple, optional)stride of the convolution default 1
padding (int or tuple, optional) zero-padding

##### Functional (torch.nn.functional)
input - input tensor of shape (minibatch X in_channels X iH X iW)
weight - filter of shape (out_channels * in_channels * kH 8 kW)
stride - the stride of the convolving kernel. Can be a single number or a tuple (sH, sW) default:1

padding - implicit zero padding on both sides of the input
Can be a single number or a tuple (padH, padW) default: 0

stride = distance where convolutional filter is applied



In [ ]:
##### OOP-based (torch.nn)
import torch
import torch.nn

image = torch.rand(16, 3, 32, 32)
conv_filter = torch.nn.Conv2d(in_channel = 3,
                             out_channel=1,
                             kernel_size=5
                             stride=1, padding=0)
output_feature = conv_filter(image)
print(output_feature.shape)



In [ ]:
##### Functional (torch.nn.functional)
import torch
import torch.nn.functional as F

image = torch.rand(16, 3, 32, 32)
filter = torch.rand(1,3,5,5)
out_feat_F = F.conv2d(image, filter, stride=1, padding=0)
print(out_feat_F.shape)

#### Convolution operator - OOP way - practice
Let's kick off this chapter by using convolution operator from the torch.nn package. You are going to create a random tensor which will represent your image and random filters to convolve the image with. Then you'll apply those images.

The torch library and the torch.nn package have already been imported for you.

Instructions
100 XP
Create 10 images with shape (1, 28, 28).
Build 6 convolutional filters of size (3, 3) with stride set to 1 and padding set to 1.
Apply the filters in the image and print the shape of the feature map.

In [8]:
import torch
import torch.nn

# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
#Build 6 convolutional filters of size (3, 3) 
#with stride set to 1 and padding set to 1
conv_filters = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=(3, 3), stride=1, padding=1)

# Convolve the image with the filters 
output_feature = conv_filters(images)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


##### Convolution operator - Functional way
While I and most of PyTorch practitioners love the torch.nn package (OOP way), other practitioners prefer building neural network models in a more functional way, using torch.nn.functional. More importantly, it is possible to mix the concepts and use both libraries at the same time (we have already done it in the previous chapter). You are going to build the same neural network you built in the previous exercise, but this time using the functional way.

As before, we have already imported the torch library and torch.nn.functional as F.

Instructions
100 XP
Create 10 random images with shape (1, 28, 28).
Create 6 random filters with shape (1, 3, 3).
Convolve the images with the filters.

In [1]:
import torch
import torch.nn.functional as F

# Create 10 random images of shape 1,28,28
image = torch.rand(10, 1, 28, 28)

# Create 6 filters of shape 1,3,3
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)



torch.Size([10, 6, 28, 28])


#### Pooling operators
Another important layers in CNS apart from convolutional operator
Convolution extracts features from image, while pooling is feature selection, choosing the most dominant features from the image by combining different features, eventualy lowering number of features and reducing computation time.

Pooling is simply lowering spatial dimensions tipycally by 2. so computations faster
2 most importan pooling operators are max pooling and average pooling.

Max selects maximum number of 4, and average calculates average of 4.

#### Max-pooling in PyTorch (OOP and Functional)


In [ ]:
### OOP Max-pooling in Pytorch
import torch
import torch.nn

im=torch.Tensor([[[3,1,3,5], [6,0,7,9], [3,2,1,4], [0,2,4,3]]])
max_pooling = torch.nn.MaxPool2d(2)
output_feature = max_pooling(im)
print(output_feature)

### Functional Max-pooling in PyTorch
import torch
import torch.nn.functional as F

im=torch.Tensor([[[3,1,3,5], [6,0,7,9], [3,2,1,4], [0,2,4,3]]])
output_feature_F=F.max_pool2d(im,2)
print(output_feature_F)

In [ ]:
### OOP Average-pooling in Pytorch
import torch
import torch.nn

im=torch.Tensor([[[3,1,3,5], [6,0,7,9], [3,2,1,4], [0,2,4,3]]])
avg_pooling = torch.nn.AvgPool2d(2)
output_feature = avg_pooling(im)
print(output_feature)

### Functional Average-pooling in Pytorch
import torch
import torch.nn.functional as F

im=torch.Tensor([[[3,1,3,5], [6,0,7,9], [3,2,1,4], [0,2,4,3]]])
output_feature_F=F.avg_pool2d(im,2)
print(output_feature_F)

#### Max-pooling operator
Here you are going to practice using max-pooling in both OOP and functional way, and see for yourself that the produced results are the same. We have already created and printed the image for you, and imported torch library in addition to torch.nn and torch.nn.Functional as F packages.

Instructions
100 XP
Build a max-pooling operator with size 2.
Apply the max-pooling operator in the image (loaded as im).
Use a max-pooling operator in functional way in the image.
Print the results of both cases.



In [2]:
import torch
import torch.nn
import torch.nn.functional as F


im = torch.rand(1, 1, 6, 6)

# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator
output_feature = max_pooling(im)

# Use pooling operator in the image
output_feature_F=F.max_pool2d(im,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[0.9583, 0.8516, 0.9719],
          [0.6846, 0.7025, 0.8354],
          [0.8008, 0.8600, 0.6248]]]])
tensor([[[[0.9583, 0.8516, 0.9719],
          [0.6846, 0.7025, 0.8354],
          [0.8008, 0.8600, 0.6248]]]])


#### Average-pooling operator
After coding the max-pooling operator, you are now going to code the average-pooling operator. You just need to replace max-pooling with average pooling.

Instructions
100 XP
Build an average-pooling operator with size 2.
Apply the average-pooling operator in the image.
Use an average-pooling operator in functional way in the image, called im.
Print the results of both cases.

In [3]:
# Build a pooling operator with size `2`.
avg_pooling = torch.nn.AvgPool2d(2)

# Apply the pooling operator
output_feature = avg_pooling(im)

# Use pooling operator in the image
output_feature_F = F.avg_pool2d(im,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[0.6729, 0.4745, 0.5138],
          [0.3597, 0.3483, 0.4595],
          [0.5460, 0.4669, 0.4094]]]])
tensor([[[[0.6729, 0.4745, 0.5138],
          [0.3597, 0.3483, 0.4595],
          [0.5460, 0.4669, 0.4094]]]])


Fantastic job, now you know to apply different types of pooling in addition to convolutions. The moment of truth has arrived, in the lext lecture we are going to learn building convolutional neural networks, the most important technique in the entire field of machine learning.

#### Building Convolutional Neural Networks

##### AlexNet in PyTorch

In [ ]:
class AlexNet(nn.Module):
    def __init__(self, num_classes=1000):
        super(AlexNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2)
        self.conv2 = nn.Conv2d(64, 192, kernel_size=5, padding=2)
        self.conv3 = nn.Conv2d(192, 384, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(384, 256, kernel_size=3, padding=1)
        self.conv6 = nn.Conv2d(256, 256, kernel_size=3, padding=1)
        self.avgpool = nn.AdaptiveAvgPool2d((6,6))
        self.fc1 = nn.Linear(256*6*6, 4096)
        self.fc1 = nn.Linear(4096, 4096)        
        self.fc1 = nn.Linear(4096, num_classes)
    
    
#than forward method
    def forward(self,x):
        x = self.relu(self.conv1(x))
        x=self.maxpool(x)
        x= self.relu(self.conv2(x))
        x=self.maxpool(x)
        x=self.relu(self.conv3(x))
        x=self.relu(self.conv4(x))
        x=self.relu(self.conv5(x))
        x=self.maxpool(x)
        x=self.avgpool(x)
        x=x.view(x.size(0), 256*6*6)
        x=self.relu(self.fc1(x))
        x=self.relu(self.fc2(x))
        return self.fc3(x)
net=AlexNet()

##### Your first CNN - __init__ method
You are going to build your first convolutional neural network. You're going to use the MNIST dataset as the dataset, which is made of handwritten digits from 0 to 9. The convolutional neural network is going to have 2 convolutional layers, each followed by a ReLU nonlinearity, and a fully connected layer. We have already imported torch and torch.nn as nn. Remember that each pooling layer halves both the height and the width of the image, so by using 2 pooling layers, the height and width are 1/4 of the original sizes. MNIST images have shape (1, 28, 28)

For the moment, you are going to implement the __init__ method of the net. In the next exercise, you will implement the .forward() method.

NB: We need 2 pooling layers, but we only need to instantiate a pooling layer once, because each pooling layer will have the same configuration. Instead, we will use self.pool twice in the next exercise.

Instructions
100 XP
Instructions
100 XP
Instantiate two convolutional filters: the first one should have 5 channels, while the second one should have 10 channels. The kernel_size for both of them should be 3, and both should use padding=1. Use the names of the arguments (instead of using 1, use padding=1).
Instantiate a ReLU() nonlinearity.
Instantiate a max pooling layer which halves the size of the image in both directions.
Instantiate a fully connected layer which connects the units with the number of classes (we are using MNIST, so there are 10 classes).

In [ ]:
import torch
import torch.nn


#MNIST dataset

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate two convolutional layers
        #Instantiate two convolutional filters: the first one should have 5 channels,
        #while the second one should have 10 channels.
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU(inplace=True)
        
        # Instantiate a max pooling layer which halves the size of the image in both directions.
        # so we set kernel_size to 2 and stride to 2
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Instantiate a fully connected layer
        # Instantiate a fully connected layer which #connects the units with the number
        #of classes (we are #using MNIST, so there are 10 classes).
        self.fc = nn.Linear(7*7*10, 10)

        
       # Great job! Now all that remains is implementing the forward() method and you have your first CNN.

#### Your first CNN - forward() method
Now that you have declared all the parameters of your CNN, all you need to do is to implement the net's forward() method, and voila, you have your very first PyTorch CNN.

Note: for evaluation purposes, the entire code of the class needs to be in the script. We are using the __init__ method as you have coded it on the previous exercise, while you are going to code the .forward() method here.

Instructions
100 XP
Instructions
100 XP
Apply the first convolutional layer, followed by the relu nonlinearity, then in the next line apply max-pooling layer.
Apply the second convolutional layer, followed by the relu nonlinearity, then in the next line apply max-pooling layer.
Transform the feature map from 4 dimensional to 2 dimensional space. The first dimension contains the batch size (-1), deduct the second dimension, by multiplying the values for height, width and depth.
Apply the fully-connected layer and return the result.

In [ ]:
class Net(nn.Module):
    def __init__(self, num_classes):
        super(Net, self).__init__()
		
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(2, 2)
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(7 * 7 * 10, 10)

    def forward(self, x):

        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv1(x))
        x = self.pool(x)

        # Apply conv followd by relu, then in next line pool
        x = self.relu(self.conv2(x))
        x = self.pool(x)

        # Prepare the image for the fully connected layer
        #Your image started with shape (28, 28) and on it were performed 2 pooling layers,
        #each halving the size. Second conv layer had 10 channels. What should be the second
        #argument of view?
        x = x.view(-1, 7 * 7 * 10)

        # Apply the fully connected layer and return the result
        return self.self.fc(x)

#### Training Convolutional Neural Networks
not much difference training neural networks from convolutional neueral networks
so, will just start from pytorch code

In [7]:
# do all necessary imports

import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# create trainloader and testloader
transform = transforms.Compose(
[transforms.ToTensor(),
transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root = './data', train=True,
                                       download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root = './data', train=False,
                                       download=True, transform=transform)

testloader = torch.utils.data.DataLoader(testset, batch_size=128, shuffle=False, num_workers=2)

#### building a CNN
class Net(nn.Module):
    def __init__(self, num_classes):
        super(Net, self).__init__()
		
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU()
        
        # Instantiate two convolutional layers
        #progressivly increase number of channels
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(2, 2)
        
        # Instantiate a fully connected layer
        #first number number of units from last layer
        #set number of classes to 10
        num_classes=10
        self.fc = nn.Linear(128 * 4 * 4, num_classes)
        
        ### apply forward method
        def forward(self, x):
            #relu convolutions
            x = self.pool(F.relu(self.conv1(x)))
            x = self.pool(F.relu(self.conv2(x)))
            x = self.pool(F.relu(self.conv3(x)))
            #pooling layer
            x = x.view(-1, 128 * 4 * 4)
            # Apply the fully connected layer and return the result
            return self.self.fc(x)        
    
#instantiate class net
net = Net()
#set loss function
criterion = nn.CrossEntropyLoss()
#set optimizer Adam, learning rate #set optimizer Adam, learning rate 3e-4
optimizer = optim.Adam(net.parameters(), lr=3e-4)

#loop multiple times
for epoch in range(10):
    for i, data in enumerate(trainloader, 0):
        #get the inputs
        inputs, labels = data
        #zero the parameter gradients
        optimizer.zero_grad()
        #forward + backward +optimize
        outputs=net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

print('finished training')



#evaluating results
corrent, total = 0,0
predictions = []
net.eval()
for i, data in enumerate(testloader, 0):
    inputs,labels = data
    outputs = net(inputs)
    _, predicted = torch.max(outputs.data, 1)
    predictions.append(outputs)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    
print('the testing set accuracy of the network is: %d %%' % (
        100 * correct /total))

Files already downloaded and verified
Files already downloaded and verified


TypeError: __init__() missing 1 required positional argument: 'num_classes'

#### Training CNNs
Similarly to what you did in Chapter 2, you are going to train a neural network. This time however, you will train the CNN you built in the previous lesson, instead of a fully connected network. The packages you need have been imported for you and the network (called net) instantiated. The cross-entropy loss function (called criterion) and the Adam optimizer (called optimizer) are also available. We have subsampled the training set so that the training goes faster, and you are going to use a single epoch.

Instructions
100 XP
Compute the predictions from the net.
Using the predictions and the labels, compute the loss function.
Compute the gradients for each weight.
Update the weights using the optimizer

In [9]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate two convolutional layers
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        
        # Instantiate the ReLU nonlinearity
        self.relu = nn.ReLU(inplace=True)
        
        # Instantiate a max pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Instantiate a fully connected layer
        self.fc = nn.Linear(49 * 10, 10)
        
    def forward(self, x):
        # Apply conv followed by relu, then in next line pool
        x = self.relu(self.conv1(x))
        x = self.pool(x)
        
        # Apply conv followed by relu, then in next line pool
        x = self.relu(self.conv2(x))
        x = self.pool(x)
        
        # Prepare the image for the fully connected layer
        x = x.view(-1, 7 * 7 * 10)
        
        # Apply the fully connected layer and return the result
        return self.fc(x)

In [10]:
import torchvision.transforms as transforms

# Transform the data to torch tensors and normalize it
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307), (0.3081))
])

# Preparing the training and test set
trainset = torchvision.datasets.MNIST('mnist', train=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, transform=transform)

# Prepare loader
train_loader = torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=True, num_workers=0)
test_loader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False, num_workers=0)
import torch.optim as optim

net = Net()
optimizer = optim.Adam(net.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()


Instructions
100 XP
Compute the predictions from the net.
Using the predictions and the labels, compute the loss function.
Compute the gradients for each weight.
Update the weights using the optimizer

In [11]:
for i, data in enumerate(train_loader, 0):
    inputs, labels = data
    optimizer.zero_grad()
    
    # Compute the forward pass
    outputs = net(inputs)
    
    # Compute the loss function
    loss = criterion(outputs, labels)
    
    # Compute the gradients
    loss.backward()
    
    # Update the weights
    optimizer.step()

Using CNNs to make predictions
Building and training neural networks is a very exciting job (trust me, I do it every day)! However, the main utility of neural networks is to make predictions. This is the entire reason why the field of deep learning has bloomed in the last few years, as neural networks predictions are extremely accurate. On this exercise, we are going to use the convolutional neural network you already trained in order to make predictions on the MNIST dataset.

Remember that torch.max() takes two arguments: -output.data - the tensor which contains the data.

Either 1 to do argmax or 0 to do max

Iterate over the given test_loader, saving the results of each iteration in data.
Get the image and label from the data tuple, storing the results in image and label.
Make a forward pass in the net using your image.
Get the net prediction using torch.max() function.


LETS SEE How accurate predictions are:


In [12]:
net.eval()
# Iterate over the data in the test_loader
for i, data in enumerate(test_loader):
    # Get the image and label from data
    image, label = data
    
    # Make a forward pass in the net with your image
    output = net(image)
    
    # Argmax the results of the net
    _, predicted = torch.max(output.data, 1)
    
    if predicted == label:
        print("Yipes, your net made the right prediction " + str(predicted))
    else:
        print("Your net prediction was " + str(predicted) + ", but the correct label is: " + str(label))
        
    if i > 10:
        break

Yipes, your net made the right prediction tensor([7])
Yipes, your net made the right prediction tensor([2])
Yipes, your net made the right prediction tensor([1])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([1])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([9])
Yipes, your net made the right prediction tensor([5])
Yipes, your net made the right prediction tensor([9])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([6])


### Using Convolutional Neural Networks
In this last chapter, we learn how to make neural networks work well in practice, using concepts like regularization, batch-normalization and transfer learning.


https://campus.datacamp.com/courses/introduction-to-deep-learning-with-pytorch/using-convolutional-neural-networks?ex=1

##### The sequential module
sequential module - PyTorch tool that allows to train neural networks in easier way


###### AlexNet declaring the modules


In [ ]:
class AlexNet(nn.Module):
    
    def __init__(self, num_classes=1000):
        super(AlexNet, self).__init__()
        self.conv1 == nn.Conv2d(3, 64, kernel_size=11, stride = 4, padding = 2)
        self.relu == nn.ReLU(inplace=True)
        self.maxpool == nn.MaxPool2d(kernel_size=3, stride=2)
        self.conv2 == nn.Conv2d(64, 192, kernel_size=5, padding = 2)
        self.conv3 == nn.Conv2d(192, 384, kernel_size=3, padding = 1)
        self.conv4 == nn.Conv2d(384, 256, kernel_size=3, padding = 1)
        self.conv5 == nn.Conv2d(256, 256, kernel_size=3, padding = 1)
        self.avgpool = nn.AdaptiveAvgPool2d((6,6))
        self.fc1 = nn.Linear(256 * 6 * 6, 4096)
        self.fc2 = nn.Linear(4096, 4096)
        self.fc3 = nn.Linear(4096, num_classes)
    #apply each of these layers sequentially
    def forward(self,x):
        x=self.relu(self.conv1(x))
        x=self.maxpool(x)
        x=self.relu(self.conv2(x))
        x=self.maxpool(x)
        x=self.relu(self.conv3(x))
        x=self.relu(self.conv4(x))
        x=self.relu(self.conv5(x))
        x=self.maxpool(x)
        x=self.avgpool(x)
        x=x.view(x.size(0), 256 * 6 * 6)
        x=self.relu(self.fc1(x))
        x=self.relu(self.fc2(x))
        return self.fc3(x)
    
net = AlexNet()

A lot of code to write, but fortunately can write in sequential module, declaring the modules


In [ ]:
class AlexNet(nn.Module):
    
    def __init__(self, num_classes=1000):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=11, stride = 4, padding = 2),nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(64, 192, kernel_size=5, padding = 2),nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(192, 384, kernel_size=3, padding = 1),nn.ReLU(inplace=True),
            nn.Conv2d(384, 256, kernel_size=3, padding = 1),nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding = 1),nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
        self.avgpool = nn.AdaptiveAvgPool2d((6,6))
        #sequential module
        self.classifier = nn.Sequential(
            nn.Dropout(), nn.Linear(256 * 6 * 6, 4096), nn.Relu(inplace=True),
            nn.Dropout(), nn.Linear(4096, 4096), nn.ReLU(inplace=True), nn.Linear(4096, num_classes),)
            
    def forward(self,x):
        x=self.features(x)
        x=self.avgpool(x)
        x=x.view(x.size(0), 256 * 6 * 6)
        x=self.classifier(x)
        return x

#### Sequential module - init method
Having learned about the sequential module, now is the time to see how you can convert a neural network that doesn't use sequential modules to one that uses them. We are giving the code to build the network in the usual way, and you are going to write the code for the same network using sequential modules.

class Net(nn.Module):
    def __init__(self, num_classes):
        super(Net, self).__init__()

        self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(in_channels=20, out_channels=40, kernel_size=3, padding=1)

        self.relu = nn.ReLU()

        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(7 * 7 * 40, 1024)
        self.fc2 = nn.Linear(1024, 2048)
        self.fc3 = nn.Linear(2048, 10) 
We want the pooling layer to be used after the second and fourth convolutional layers, while the relu nonlinearity needs to be used after each layer except the last (fully-connected) layer. For the number of filters (kernels), stride, passing, number of channels and number of units, use the same numbers as above.

Instructions
Declare all the layers needed for feature extraction in the self.features.
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Declare all the layers for feature extraction
        self.features = nn.Sequential(nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1), 
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=____, out_channels=____, kernel_size=____, padding=____), 
                                      nn.MaxPool2d(2, 2), nn.ReLU(inplace=True),
                                      nn.Conv2d(____=____, ____=____, ____=____, ____=____), 
                                      nn.ReLU(____=____),
                                      nn.Conv2d(____=____, ____=____, ____=____, ____=____), 
                                      nn.MaxPool2d(____, ____), nn.ReLU(____=____))
                                        # Declare all the layers for classification
        self.classifier = nn.Sequential(nn.Linear(____ * ____ * ____, 1024), nn.ReLU(____=____),
                                       	nn.Linear(____, ____), nn.ReLU(____=____),
                                        nn.Linear(____, ____))

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Declare all the layers for feature extraction
        self.features = nn.Sequential(nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1), 
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1), 
                                      nn.MaxPool2d(2, 2), nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, padding=1), 
                                      nn.ReLU(inplace=True),
                                      nn.Conv2d(in_channels=20, out_channels=40, kernel_size=3, padding=1), 
                                      nn.MaxPool2d(2, 2), nn.ReLU(inplace=True))
        # Declare all the layers for classification
        self.classifier = nn.Sequential(nn.Linear(7 * 7 * 40, 1024), nn.ReLU(inplace=True),
                                       	nn.Linear(1024, 2048), nn.ReLU(inplace=True),
                                        nn.Linear(2048, 10))

Great job! You're ready to implement the forward() method using the sequential modules you just wrote.

##### sequentiall module - forward() method
Now, that you have defined all the modules that the network needs, it is time to apply them in the forward() method. For context, we are giving the code for the forward() method, if the net was written in the usual way.
Note: for evaluation purposes, the entire code of the class needs to be in the script. We are using the __init__ method as you have coded it on the previous exercise, while you are going to code the forward() method here.

Instructions
100 XP
Extract the features from the images.
Squeeze the three spatial dimensions of the feature maps into one using the view() method.
Classify images based on the extracted features.
    def forward(self, x):
      
        # Apply the feature extractor in the input
        x = ____
        
        # Squeeze the three spatial dimensions in one
        x = x.view(-1, ____ * ____ * ____)
        
        # Classify the images
        x = ____
        return x

In [ ]:
    def forward(self, x):
      
        # Apply the feature extractor in the input
        x = self.features(x)
        
        # Squeeze the three spatial dimensions in one
        x = x.view(-1, 7 * 7 * 40)
        
        # Classify the images
        x = self.classifier(x)
        return x

Nice! You can see how the forward() method simplifies the whole process.

#### The problem of overfitting

How to prevent overfitting
Training set
Validation set
Testing set

Validation set:   cross-validation  ( no overlapping of datasets)
Training set: train the model as before
Validation set: select the model  (best model based on validation set)
Testing set: test the model

###### Creating validation sets in PyTorch


In [ ]:
indices = np.arrange(50000)
np.random.suffle(indices)
train_loader = torch.utils.data.DataLoader(
    datasets.CIFAR10(root='./data', train=True, download=True,
                    transform=transforms.Compose([transoforms.ToTensor(),
                    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))])),
    #first 45000 for training
    batch_size=1, suffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[:45000]))

val_loader = torch.utils.data.DataLoader(
datasets.CIFAR10(root='./data', train=True, download=True,
                transform=transforms.Compose([transforms.ToTensor(),
                transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))])),
    #last 5000 for validation
batch_size=1, shuffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[45000:50000]))



#### Validation set
You saw the need for validation set in the previous video. Problem is that the datasets typically are not separated into training, validation and testing. It is your job as a data scientist to split the dataset into training, testing and validation. The easiest (and most used) way of doing so is to do a random splitting of the dataset. In PyTorch, that can be done using SubsetRandomSampler object. You are going to split the training part of MNIST dataset into training and validation. After randomly shuffling the dataset, use the first 55000 points for training, and the remaining 5000 points for validation.

Instructions
100 XP
Use numpy.arange() to create an array containing numbers [0, 59999] and then randomly shuffle the array.
In the train_loader using SubsetRandomSampler() use the first 55k points for training.
In the val_loader use the remaining 5k points for validation.

# Shuffle the indices
indices = ____
np.____

# Build the train loader
train_loader = torch.utils.data.DataLoader(datasets.MNIST('mnist', download=True, train=True,
                     transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                     batch_size=64, shuffle=____, sampler=torch.utils.data.SubsetRandomSampler(indices[:____]))

# Build the validation loader
val_loader = torch.utils.data.DataLoader(datasets.MNIST('mnist', download=True, train=True,
                   transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                   batch_size=64, shuffle=____, sampler=____)

In [3]:
import numpy as np
import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
# Shuffle the indices
indices = np.arange(60000)
np.random.shuffle(indices)

# Build the train loader
train_loader = torch.utils.data.DataLoader(datasets.MNIST('mnist', download=True, train=True,
                     transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                     batch_size=64, shuffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[:55000]))

# Build the validation loader
val_loader = torch.utils.data.DataLoader(datasets.MNIST('mnist', download=True, train=True,
                   transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                   batch_size=64, shuffle=False, sampler=torch.utils.data.SubsetRandomSampler(indices[55000:]))

Detecting overfitting
Overfitting is arguably the biggest problem in machine learning and data science, and being able to detect it will make you a much better data scientist. While reaching a high (or even perfect) accuracy on training sets is quite easy when you use neural networks, reaching a high accuracy on validation and testing sets is a very different thing.

Let's see if you can now detect overfitting. Amongst the accuracy scores below, which network presents the biggest overfitting problem. ?


The accuracy in the training set is 90%, the accuracy in the validation set is 70%.
press

Bravo, this is the correct answer! The accuracy in the training set is much higher than in the validation set, this is a typical example of overfitting.


#### Regulatization techniques

###### L2 - regularization

#just add weight_decay order in optimizer

optimizer = optim.Adam(net.parameters(), lr=3e-4, weight_decay=0.0001)

###### Dropout
During the pass there is a probability of drop out at each computation
Used in fully connected layers


Can be used in AlexNet example
self.classifier = nn.Sequential(
#drop at each unit with probability of 50% p=0.5
    nn.Dropout(p=0.5),
    nn.Linear(256 * 6 * 6, 4096),
    nn.ReLU(inplace=True),
    nn.Dropout(p=0.5),
    nn.Linear(4096, 4096),
    nn.ReLU(inplace=True),
    nn.Linear(4096, num_classes),
    )
    
###### Batch-normalization (for large neural networks)
self.bn = nn.BatchNorm2d(num_features=64, eps=1e-05, momentum=0.9)


###### Early - stopping
at the end of training we use the best performing network


Hyperparameters, how to choose:
l2 regulatization, dropout parameter, optimizers (Adam vs gradient descent), batch-norm momentum and epsilon, number of epochs for early stopping)

Answer: Train many networks with different hyperparameters (typically use random values for them), and test them in the validation set. They use the best performing net in the validation set to know the expected accuracy of the network in new data

Some regularization technique perform differently when net is getting trained or is getting validated
eval() mode

#sets the net in the train mode
model.train()

#sets the net in evaluation mode
model.eval()


###### L2-regularization
You are going to implement each of the regularization techniques explained in the previous video. Doing so, you will also remember important concepts studied throughout the course. You will start with l2-regularization, the most important regularization technique in machine learning. As you saw in the video, l2-regularization simply penalizes large weights, and thus enforces the network to use only small weights.

Instructions
100 XP
Instantiate an object called model from class Net(), which is available in your workspace (consider it as a blackbox).
Instantiate the cross-entropy loss.
Instantiate Adam optimizer with learning_rate equals to 3e-4, and l2 regularization parameter equals to 0.001.

In [ ]:
# Instantiate the network
model = Net()

# Instantiate the cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Instantiate the Adam optimizer with learning_rate equals # to 3e-4, and l2 regularization parameter equals to 0.001
optimizer = optim.Adam(model.parameters(), lr=3e-4, weight_decay=0.001)

Cool! See how easy it is to use l2 regularization in PyTorch? When you will start using bigger networks, this might well make the difference between your network overfitting or not.

#### Dropout
You saw that dropout is an effective technique to avoid overfitting. Typically, dropout is applied in fully-connected neural networks, or in the fully-connected layers of a convolutional neural network. You are now going to implement dropout and use it on a small fully-connected neural network.

For the first hidden layer use 200 units, for the second hidden layer use 500 units, and for the output layer use 10 units (one for each class). For the activation function, use ReLU. Use .Dropout() with strength 0.5, between the first and second hidden layer. Use the sequential module, with the order being: fully-connected, activation, dropout, fully-connected, activation, fully-connected.

Instructions 1/2
50 XP
1
2
Implement the __init__ method, based on the description of the network in the context.

In [ ]:
class Net(nn.Module):
    def __init__(self):
        # Define all the parameters of the net
        self.classifier = nn.Sequential(
            nn.Linear(28 * 28, 200),
            nn.ReLU(inplace=True),
            #dropout betwenn first and second sequential layer
            nn.Dropout(p=0.5),
            nn.Linear(200, 500),
            nn.ReLU(inplace=True),
            nn.Linear(500, 10)
        )
        
    def forward(self, x):
        # Do the forward pass
        return self.classifier(x)

Great job! You now know how to efficiently regularize fully-connected layers.
#### Batch-normalization
Dropout is used to regularize fully-connected layers. Batch-normalization is used to make the training of convolutional neural networks more efficient, while at the same time having regularization effects. You are going to implement the __init__ method of a small convolutional neural network, with batch-normalization. The feature extraction part of the CNN will contain the following modules (in order): convolution, max-pool, activation, batch-norm, convolution, max-pool, relu, batch-norm.

The first convolutional layer will contain 10 output channels, while the second will contain 20 output channels. As always, we are going to use MNIST dataset, with images having shape (28, 28) in grayscale format (1 channel). In all cases, the size of the filter should be 3, the stride should be 1 and the padding should be 1.

Instructions
100 XP
Implement the feature extraction part of the network, using the description in the context.
Implement the fully-connected (classifier) part of the network.

In [ ]:
    def __init__(self):
        super(Net, self).__init__()
        
        # Implement the sequential module for feature extraction
        self.features = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=10, kernel_size=3, stride=1, padding=1),
            nn.MaxPool2d(2, 2), nn.ReLU(inplace=True), nn.BatchNorm2d(10),
            nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, stride=1, padding=1),
            nn.MaxPool2d(2, 2), nn.ReLU(inplace=True), nn.BatchNorm2d(20)
        )
        
        # Implement the fully connected layer for classification
        self.fc = nn.Linear(in_features=20 * 7 * 7, out_features=10)

#### Transfer learning


###### Finetuning in PyTorch


In [ ]:
# Instantiate the model
model = Net()

#first load the old model
model.load_state_dict(torch.load('cifar10_net_pth'))

#change the number of units in the last layer = number of out channels
model.fc = nn.Linear(4 * 4 * 1024, 100)
# train and evaluate model, procedure is the same
model.train()


####### Freezing the layers
#instantiate the model
model= Net()

#load the parameters from the old model
model.load_state_dict(torch.load('cifar10_net.pth'))

#interate over the parameters on the model
#freeze all the layers bar the final one
for param in model.parameters():
    param.requires_grad = False
    
#change the number of output units
#in this case only final layer in updated
model.fc = nn.Linear(4 * 4 * 1024, 100)

#train and evaluate the model
model.train()

##### Torchvision
Torchvision is a PyTorch library with many pretrained networks, ready to be used for your dataset
For example you can use state of art models like resnet, by simply downloading them from torchvision with a single line of code as shown here.

Than you just need to change number of units to number of classes in your dataset, and voila you have a very good net ready to be used without even needing to write the code for it.


So, always consider finetuning an already pretrained net


In [ ]:
#torchvision library
import torchvision
model = torchvision.models.resnet18(pretrained=True)
model.fc = nn.Linear(512, num_classes)

#### Finetuning a CNN
Previously, you trained a model to classify handwritten digits and saved the model parameters to my_net.pth. Now you're going to classify handwritten letters, but you have a smaller training set.

In the first step, you'll create a new model using this training set, but the accuracy will be poor. Next, you'll perform the same training, but you'll start with the parameters from your digit classifying model. Even though digits and letters are two different classification problems, you'll see that using information from your previous model will dramatically improve this one.

Instructions 1/2
50 XP
1
2
Create a new model using the Net() module.
Change the number of output units, to the number of classifications for letters.

#Create a new model
model = ____

#Change the number of out channels
model.fc = nn.Linear(7 * 7 * 512, ____)

#Train and evaluate the model
model.train()
train_net(model, optimizer, criterion)
print("Accuracy of the net is: " + str(model.eval()))

In [ ]:
# Create a new model
model = Net()

# Change the number of output units
model.fc = nn.Linear(7 * 7 * 512, 26)

# Train and evaluate the model
model.train()
train_net(model, optimizer, criterion)
print("Accuracy of the net is: " + str(model.eval()))

#### Torchvision module
You already finetuned a net you had pretrained. In practice though, it is very common to finetune CNNs that someone else (typically the library's developers) have pretrained in ImageNet. Big networks still take a lot of time to be trained on large datasets, and maybe you cannot afford to train a large network on a dataset of 1.2 million images on your laptop.

Instead, you can simply download the network and finetune it on your dataset. That's what you will do right now. You are going to assume that you have a personal dataset, containing the images from all your last 7 holidays. You want to build a neural network that can classify each image depending on the holiday it comes from. However, since the dataset is so small, you need to use the finetuning technique.

In [ ]:
import torchvision

# Download resnet18
model = torchvision.models.resnet18(pretrained=True)

# Freeze all the layers bar the last one
for param in model.parameters():
    param.requires_grad = False
    
# Change the number of output units
model.fc = nn.Linear(512, 7)

##### Finetuning a CNN
Previously, you trained a model to classify handwritten digits and saved the model parameters to my_net.pth. Now you're going to classify handwritten letters, but you have a smaller training set.

In the first step, you'll create a new model using this training set, but the accuracy will be poor. Next, you'll perform the same training, but you'll start with the parameters from your digit classifying model. Even though digits and letters are two different classification problems, you'll see that using information from your previous model will dramatically improve this one.

Instructions 2/2
50 XP
2
Repeat the training process, but first load the digit classifier parameters from my_net.pth.

In [ ]:
# Create a model using
model = Net()

# Load the parameters from the old model
model.load_state_dict(torch.load('my_net.pth'))

# Change the number of out channels
model.fc = nn.Linear(7 * 7 * 512, 26)

# Train and evaluate the model
model.train()
train_net(model, optimizer, criterion)
print("Accuracy of the net is: " + str(model.eval()))

Excellent! By incorporating information from the previously trained model, we are able to get a good model for handwritten digits, even with a small training set!